import type { Metadata } from "next";
import WalletProvider from "@/wagmi/walletProvider";
import './globals.css'
import { ThemeProvider } from "@material-tailwind/react";
import customTheme from '@/materialTailwind/themeConfig'
import MaterialTailwindThemeProvider from "@/materialTailwind/ThemeProvider";
import { StickyNavbar } from "@/components/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <WalletProvider>
          <MaterialTailwindThemeProvider>
            <StickyNavbar />
            {children}
          </MaterialTailwindThemeProvider>
        </WalletProvider>
      </body>
    </html>
  );
}
